server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://ec2-3-34-251-37.ap-northeast-2.compute.amazonaws.com:3306/unnamed
#    url: jdbc:mysql://localhost:3306/unnamed?useSSL=false&&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace